# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Signup' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'signup' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1920, 1012)
    @driver.find_element(:css, '.btn-warning').click
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('avm04@gmail.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('1234567890')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('0987654321')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, 'html').click
    @driver.find_element(:css, '.col-md-6').click
    expect(@driver.find_element(:css, '.alert').text).to eq('Password confirmation doesn\\\'t match Password')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('1234567890')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('1234567890')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, 'td:nth-child(1)').click
    expect(@driver.find_element(:css, 'td:nth-child(1)').text).to eq('Logged in as: avm04@gmail.ru')
  end
end
