# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет добавление админом записей
describe 'Adminaddnewrecord' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'adminaddnewrecord' do
    # Пользователь входит на сайт
    @driver.get('http://localhost:3000/')
    # Авторизуется как админ
    @driver.find_element(:css, '.btn-outline-light').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('admin@admin.admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123123')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.mynotice').text).to eq('Logged in successfully')
    @driver.find_element(:link_text, 'Home').click
    @driver.find_element(:css, '.btn-success').click
    # Добавлет новую запись
    @driver.find_element(:id, 'record_title').click
    @driver.find_element(:id, 'record_title').send_keys('Машина')
    @driver.find_element(:id, 'record_photo').send_keys("#{Rails.root}/spec/support/assets/1660890536_1-sportishka-com-p-samaya-rzhavaya-mashina-v-mire-krasivo-fot-1.jpg")
    @driver.find_element(:id, 'record_description').click
    @driver.find_element(:id, 'record_description').send_keys('Просто машина для аукциона')
    @driver.find_element(:name, 'commit').click
    # Проверяет что запись создана с теми параметрами, которые он вводил
    expect(@driver.find_element(:css, 'h1').text).to eq('Машина')
    expect(@driver.find_element(:css, 'p:nth-child(3)').text).to eq('Просто машина для аукциона')
    expect(@driver.find_element(:css, 'p:nth-child(4)').text).to eq('Аукцион объявлен')
  end
end
