# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет интернационализацию сайта
describe 'Changelang' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'changelang' do
    @driver.get('http://localhost:3000/en')
    @driver.find_element(:link_text, 'Contacts').click
    expect(@driver.find_element(:css, 'h1').text).to eq('We are the largest car auction company')
    @driver.find_element(:link_text, 'Russian').click
    expect(@driver.find_element(:css, 'h1').text).to eq('Мы - крупнейшая компания по аукциону автомобилей')
  end
end
