# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет сценарий регистрации пользователя, выход и вход с его данными аккаунта
describe 'Signin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email = Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'signin' do
    # Пользователь заходит на сайт
    @driver.get('http://localhost:3000/en')
    # Хочет подобрать себе машину
    @driver.find_element(:link_text, 'Find').click
    # Но система требует авторизации
    expect(@driver.find_element(:css, '.myalert').text).to eq('You must be signed in')
    @driver.find_element(:css, '.btn-warning').click
    # Пользователь регистрируется
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(@email)
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('Aq123e')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('Aq123e')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.mynotice').text).to eq('Successfully created account')
    # Выходит
    @driver.find_element(:css, '.btn:nth-child(2)').click
    # Входит со своими данными
    @driver.find_element(:css, '.btn-outline-light').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys(@email)
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Aq123e')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.mynotice').text).to eq('Logged in successfully')
  end
end
