# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'faker'
describe 'Signup' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email=Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'signup' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:css, '.btn-warning').click
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(@email)
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123321')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123123')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert').text).to eq('Password confirmation doesn\'t match Password')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123123')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123123')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'td:nth-child(1)').text).to eq("Logged in as: #{@email}")
  end
end
