# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет сценарий регистрации пользователя с промежуточной проверкой на неправильное подтверждение пароля
describe 'Signup' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email = Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'signup' do
    # Пользователь заходит на сайт
    @driver.get('http://localhost:3000/en')
    # Нажимает кнопку регистрации
    @driver.find_element(:css, '.btn-warning').click
    # Вводит данные
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(@email)
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123321')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123123')
    @driver.find_element(:name, 'commit').click
    # Поскольку введены разные пароли, то ловит ошибку
    expect(@driver.find_element(:css, '.alert').text).to eq('Password confirmation doesn\'t match Password')
    # Вводит правильные пароли
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123123')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123123')
    @driver.find_element(:name, 'commit').click
    # Успешно проходит регистрацию и проверяет, что зашел именно "под собой"
    expect(@driver.find_element(:css, 'td:nth-child(1)').text).to eq("Logged in as: #{@email}")
  end
end
