# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'faker'
# Тест проверяет сценарий регистрации пользователя НЕ со своей почтой
describe 'Signup' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email = Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'incorrect_signup' do
    # Пользователь заходит на сайт
    @driver.get('http://localhost:3000/en')
    @driver.manage.window.resize_to(1920, 1080)
    # Нажимает кнопку регистрации
    @driver.find_element(:css, '.btn-warning').click
    # Вводит данные, чтобы зарегистрироваться
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('alex@mail.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('qwerty')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('qwerty')
    @driver.find_element(:name, 'commit').click
    # Поскольку почта уже занята (добавлена в базу заранее), то ловит ошибку
    expect(@driver.find_element(:css, '.alert').text).to eq('Mail has already been taken')
  end
end
