# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'faker'
# Тест проверяет сценарий входа пользователя на сайт с корректными данными
describe 'Signin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email = Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'correct_signin' do
    # Пользователь заходит на сайт
    @driver.get('http://localhost:3000/en')
    @driver.manage.window.resize_to(1920, 1080)
    # Хочет подобрать себе машину
    @driver.find_element(:link_text, 'Find').click
    # Но система требует авторизации
    expect(@driver.find_element(:css, '.myalert').text).to eq('You must be signed in')
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('alex@mail.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Qw0987')
    @driver.find_element(:name, 'commit').click
    # Проверяем, что успешно зашел
    expect(@driver.find_element(:css, '.mynotice').text).to eq('Logged in successfully')
  end
end
