# frozen_string_literal: true

# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'faker'
# Тест проверяет списание средств со счета при создании ставки
describe 'Minusbalance' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
    @email = Faker::Internet.email
  end
  after(:each) do
    @driver.quit
  end
  it 'minusbalance' do
    # Пользователь заходит на сайт
    @driver.get('http://localhost:3000/en')
    @driver.manage.window.resize_to(1920, 1080)
    # Нажимает кнопку регистрации
    @driver.find_element(:css, '.btn-warning').click
    # Вводит данные
    @driver.find_element(:id, 'user_name').click
    @driver.find_element(:id, 'user_name').send_keys('alexander')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(@email)
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('qwerty')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('qwerty')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Find').click
    @driver.find_element(:link_text, 'More').click
    # Вводит ставку
    @driver.find_element(:id, 'comment_cost').click
    @driver.find_element(:id, 'comment_cost').send_keys('3500')
    @driver.find_element(:name, 'commit').click
    # Проверяет что заблокировалась та сумма, которую он поставил
    expect(@driver.find_element(:css, 'td:nth-child(2)').text).to eq('Balance: -3500')
  end
end
