# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет, что таймер в разные моменты времени различен
describe 'Timer' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'timer' do
    @driver.get('http://localhost:3000/en')
    @driver.manage.window.resize_to(1920, 1080)
    @driver.find_element(:css, '.btn-outline-light').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('dan@mam.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('1989rt')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Find').click
    sleep 3
    time1 = @driver.find_element(:id, '1').text
    sleep 5
    expect(@driver.find_element(:id, '1').text).not_to eq(time1)
  end
end
