# frozen_string_literal: true

# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
# Тест проверяет корректную смену языка
describe 'Lang' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'lang' do
    @driver.get('http://localhost:3000/en')
    @driver.manage.window.resize_to(1920, 1080)
    @driver.find_element(:link_text, 'Home').click
    @driver.find_element(:css, 'h1').click
    expect(@driver.find_element(:css, 'h1').text).to eq('Entrance')
    @driver.find_element(:link_text, 'РУ').click
    @driver.find_element(:css, 'h1').click
    expect(@driver.find_element(:css, 'h1').text).to eq('Вход')
  end
end
